os: linux
arch: arm64-graviton2
group: edge
language: sass
cache: bundler

branches:
  only:
  - master
rvm:
- 2.6

before_install:
- gem install sass

addons:
  apt:
    packages:
    - sshpass

script:

- sass --update sass:. --style=compressed
- rm .gitignore .sass-lint.yml README.md digitalocean.enc readme.txt rsync-exclusions.txt
- rm -r sass
-sshpass -p '$one_sftp_pwd' sftp $one_usr@$one_sftp:staging/wp-content/themes<<EOF
- put -r slow-wheels
- bye
- EOF
